// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3bTkVd9_xpDZQu5I9hDMcMCIjTaWxP9k',
    appId: '1:815652477888:web:c771b23b96d5249b7f8625',
    messagingSenderId: '815652477888',
    projectId: 'insdec-6f1a5',
    authDomain: 'insdec-6f1a5.firebaseapp.com',
    storageBucket: 'insdec-6f1a5.firebasestorage.app',
    measurementId: 'G-NFDMDS5J1X',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3bTkVd9_xpDZQu5I9hDMcMCIjTaWxP9k',
    appId: '1:815652477888:web:46639c7441b6c02d7f8625',
    messagingSenderId: '815652477888',
    projectId: 'insdec-6f1a5',
    authDomain: 'insdec-6f1a5.firebaseapp.com',
    storageBucket: 'insdec-6f1a5.firebasestorage.app',
    measurementId: 'G-5GQ89NHL6F',
  );
}
